language: swift
osx_image: xcode10.0

branches:
  only:
  - master
  - /^v.*$/
before_install:
  - rvm install ruby-2.2.2
  - gem install cocoapods
  - gem install xcpretty -N
  - brew update
script:
  - set -o pipefail
  - xcodebuild -workspace Lab_works.xcworkspace -scheme Lab_works -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
deploy:
  provider: releases
  api_key: "$Git_key"
  file : /Users/travis/Library/Developer/Xcode/DerivedData/Lab_works-fztiiouihfuodtbppihzphudsdif/Build/Products/Debug-iphonesimulator/Lab_works.app
  skip_cleanup: true
  on:
     tags: false
     all_branches: true